### ISSUE TITLE
Loosing usb device connection 

### ISSUE THREAD

**Issue by Jean-PhilippeD** [enocean-js/enocean-js#168] opened 2020-02-11 18:24 UTC
Hello,

I encountered an issue I don't understand.
After a while, my device does not receive any data.

I've tried to add some logs but I see nothing. Neither at system level through syslog... Nothing seems to happen but I do not receive any more data from my dongle.

Here is the code I use to initiate connection:

```
port = new SerialPort(usbPort, { baudRate: 57600 })
sender = SerialportSender({ port: shared.port, parser: new ESP3Parser() })
parser = new ESP3Parser()
transformer = new ESP3Transformer()
port.pipe(parser).pipe(transformer)

port.on('open', function() {
      console.info('Enocean :: Connected to enocean device ')
})

port.on('error', function(err) {
      console.log(err) // Nothing happen here
})

port.on('disconnect', function(err) {
      console.log(err) // Nothing happen here
 })

transformer.on('data', async data => {
      console.log(data) // No more data after a few hours
})
```

**Comment by Holger-Will** [comment] 2020-02-11 19:46
if in that state, can you still send data?

**Comment by Alaric84** [comment] 2020-02-11 19:58
I also observed that. No more data after a couple of houres. But only with plain node.js not within nodeRed. But I have never tried to send data then.

**Comment by Jean-PhilippeD** [comment] 2020-02-11 20:31
I did not try to send data because I did not found how to do it yet.
It's also in node app, node wihtin nodeRed.

**Comment by Holger-Will** [comment] 2020-02-16 04:53
i need some more info, as i can not reproduce this... what is your:

- operating system (version)
- node version
- enocean-js version
- npm version
- output of `npm ls`
- whatever other info i may need to pin dow the problem...

is it reproducible?

**Comment by Jean-PhilippeD** [comment] 2020-02-22 18:50
Hi,

OS: it's a Virtual machine Ubuntu 14.04.6 LTS on a KVM host
Node: v10.18
enocean-js: v0.0.10
npm: v6.13.4

As I'm running an old ubuntu, I'm currently upgrading it to the latest LTS. 
I'll see if I still got the problem.

**Comment by Jean-PhilippeD** [comment] 2020-02-24 06:34
Even with a ubuntu 18.04, the issue is still happening, so yes it is reproducible :(

**Comment by Holger-Will** [comment] 2020-02-24 08:10
thanks for the info! i'm running a test again. I'm running it with pm2 to monitor memory usage, handler count, uptime etc. You might want to try this as well so we can have some number to tackle the problem.

**Comment by Holger-Will** [comment] 2020-02-24 08:10
might be connected to: https://github.com/serialport/node-serialport/issues/1940

**Comment by Holger-Will** [comment] 2020-02-24 11:57
ok, i can now confirm the problem... looking into this.

**Comment by Holger-Will** [comment] 2020-02-25 05:38
ok, i pinned it dow to this line:

```
sender = SerialportSender({ port: shared.port, parser: new ESP3Parser() })
```

i guess it has something to do with sharing the port... investigating further...

but can you confirm that running your example without the sender will not freeze the port?

**Comment by Holger-Will** [comment] 2020-02-25 06:44
I think I found a fix for this bug... still testing though... it has to do with stream backpressure and parallel pipes where one (the parser for the return values of the sender) consumes the data slower than the other pipe... 
there are basically two solutions.
1. only pipe to parser in serialport-sender when data is actuallly send, and unpipe afterwards.
2. clone the stream when you want to share it.

i'm currently testing 1. because it's a quick fix, but it may run into the same problem in very rare occations.

option 2 does not work out of the box because node streams do not have a `tee()` method (as WebApi stream have) 
but we could use https://www.npmjs.com/package/readable-stream-clone
that should fix the problem for all cases.

**Closed** 2020-02-25 07:14 UTC
Labels: bug

**Comment by Holger-Will** [comment] 2020-02-25 07:16
i'm using https://github.com/Borewit/t-readable#readme now...
should be fixed in `0.0.14`

**Comment by Holger-Will** [comment] 2020-02-25 07:40
confirming fix running the exact same example code that caused the hang but with updated enocean-js to 0.0.14.

**Comment by Jean-PhilippeD** [comment] 2020-02-25 09:46
waou I've just read your updates ! you're amazing ;)

In my example, I've forget to tell that I indeed share my port in a shared lib so I can use it to consume or send from 2 differents libs, but you pointed that with the `shared.port` variable I let in my example :)

I will try your fix as soon as possible, I think tonight.

**Comment by Jean-PhilippeD** [comment] 2020-02-27 20:39
I confirm the problem is solved  ! thx
